### ISSUE TITLE
thread 'main' panicked at 'Bad embedded images.toml

### ISSUE THREAD

**Issue by vt-alt** [Obirvalger/vml#2]
All commands suddenly stopped to work (there was no `vml` update or anything).
```
$ RUST_BACKTRACE=1 vml sh
thread 'main' panicked at 'Bad embedded images.toml: Error { inner: ErrorInner { kind: Custom, line: Some(197), col: 0, at: Some(6312), message: "unknown field `properties`, expected one of `description`, `url`, `get-url-prog`, `change`, `update-after-days`, `arch-mapping`", key: ["alt-gui"] } }', src/images.rs:308:10
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::expect
             at /usr/src/RPM/BUILD/rust-1.61.0/library/core/src/result.rs:1035:23
   4: vml::images::update_images_file
             at ./src/vml/src/images.rs:307:31
   5: vml::main
             at ./src/vml/src/main.rs:320:5
   6: core::ops::function::FnOnce::call_once
             at /usr/src/RPM/BUILD/rust-1.61.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by vt-alt** [comment]
There was `git pull --rebase` thought, but no `cargo build`. After `cargo build` it started to work again.
